### ISSUE TITLE
[Question] 이벤트 스토어의 이벤트 발행 실패 처리

### ISSUE THREAD

**Issue by gongdo** [loom/loom-dotnet#1]
Loom의 이벤트 스토어 구현체를 보면
https://github.com/loom/loom-dotnet/blob/master/source/Loom.EventSourcing.EntityFrameworkCore/EntityEventStore.cs#L51-L52
와 같이 1) 이벤트를 저장하고 2) 발행되지 않은(pending) 이벤트를 발행 하도록 되어있습니다.

이벤트 저장소와 이벤트 발행의 대상이 다르므로 저장에는 성공하되 발행은 실패(예외 발생)할 가능성이 있습니다.

이 경우 이 이벤트를 발생시킨 코드에서는 예외처리가 다소 모호할 수 있을 것 같습니다.
1) 어쨌든 예외이므로 오류 처리를 한다.
-> 호출자는 요청이 예외 처리가 되어버렸기 때문에 아마도 같은 동작을 재시도 하려고 할 것이며 애플리케이션은 이 요청이 중복처리 되지 않도록 논리적으로 방어해야 한다. 또한 시스템은 발행되지 않은 이벤트를 가능한 빠르고 자동으로 재발행 할 수 있는 매커니즘을 준비해야 한다.
2) 이벤트 발행 예외는 삼킨다.
-> 애초에 호출자는 이벤트 저장만을 의도했기 때문에 문제가 없다. 1)과 마찬가지로 시스템은 미발행 이벤트를 처리하는 매커니즘이 필요하다.

1)은 경우에 따라 매우 곤란할 수 있을 것 같습니다. 예를 들어 특정한 Id의 주문을 넣는 동작이라면 같은 Id의 주문이 이미 들어갔으니 이미 주문되었다는 처리를 할 수 있겠지만 특정 액션을 카운팅하는 동작이라면 호출자는 아마도 동작이 실패한줄 알고 여러번 호출할 수 있겠습니다.
2)는 예외를 삼킨다는게 매우 찝찝하지만 전반적인 처리는 훨씬 편할것 같습니다.

https://github.com/loom/loom-dotnet/blob/master/source/Loom.EventSourcing.EntityFrameworkCore/FlushEntityEventsCommandExecutor.cs
쌓인 미발행 이벤트를 강제로 해소하는 커맨드를 별도로 처리하는 커맨드가 있는 걸로 봐서 아마도 Loom을 사용하는 애플리케이션은 수동이든 자동이든 미발행 이벤트 처리를 하고 있다고 예상합니다.

이벤트 스토어 구현체에서 이벤트 저장은 성공하고 발행에 실패할 경우 어떻게 처리하는게 좋다고 생각하시는지 여쭤봅니다.
또한 위의 커맨드는 어떤 식으로 호출하는지도 궁금합니다.

**Comment by gyuwon** [comment]
저도 1번은 바람직하지 않다고 생각합니다만 현재로서는 사용하는 입장에선 1번이 되어버릴 가능성이 높네요. `PublishPendingEvents` 메서드가 특별한 형식의 예외를 던지거나, 별도의 발행오류 처리 경로를 API로 열어주는 것이 어떨까 싶습니다.

`FlushEntityEvents` 명령은 `PendingEntityEventScanner` 클래스가 발행합니다. 단, 이 클래스의 `ScanPendingEvents` 메서드를 호출하는 책임은 클라이언트가 가집니다. 제가 사용할 때엔 Azure Functions `[TimerTrigger]` 트리거로 1분에 한 번 정도씩 실행하려고 합니다.

**Comment by mhyeon-lee** [comment]
@gyuwon 
본문 질문 내용에서 확장되는 이야기지만, 궁금한 부분이 있어서 질문합니다.

이벤트 저장 후 발행에 실패하는 경우 저장소에 Pending 된 이벤트가 남아 있게 되고
`FlushEntityEvents` 명령 또는 뒤이어 실행되는 Command 에 의해 Pending 된 이벤트가 발행될거 같습니다.

이 명령들에 의한 프로세스들이 동시에 이벤트 저장소에 접근할 경우 Pending 된 이벤트를 각자 읽어가서 발행할 수 있을거 같은데, 이런 동시 접근으로 인한 이벤트 중복 발행은 어떻게 제어하시는지 궁금합니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 다음 코드를 보시면 말씀하신 문제를 해결하기 위해 `FlushEvents` 명령을 보낼 때 스트림 식별자를 파티션 키로 사용합니다. Kafka 등의 파티셔닝을 지원하는 메시지 중개자를 사용하면 하나의 스트림에 대해 동시에 최대 하나의 이벤트를 발행하는 프로세서만 동작하게 되겠죠.

https://github.com/loom/loom-dotnet/blob/6315ef9f8c2bcb01523455887a35880a9d2e7d78/source/Loom.EventSourcing.EntityFrameworkCore/EntityPendingEventScanner.cs#L46

**Comment by gyuwon** [comment]
이 이슈는 닫겠습니다. 추가 의견 있으신 분은 다시 열어주세요. :)
